### ISSUE TITLE
Pi user password

### ISSUE THREAD

**Issue by nichmorgan** [nosix/raspberry-gpio-emulator#11]
Hi,

I'm trying the default Pi user password in the docker image, but it's not working. Can you share the password for this user?

**Comment by nosix** [comment]
If you follow the usage instructions displayed at the URL below, there should be no login process involved. Since I am unsure about what password you are being asked for, I am unable to provide an answer.

https://hub.docker.com/r/nosix/raspberry-gpio-emulator/

**Comment by nichmorgan** [comment]
Hi nosix, thank you for your quick reply. I am referring to the sudo password because I'm trying to install some things in the image.

**Comment by nosix** [comment]
This image is based on the ubuntu-vnc-desktop image. For use cases other than those intended, please refer to ubuntu-vnc-desktop.

https://github.com/fcwu/docker-ubuntu-vnc-desktop

**Comment by nichmorgan** [comment]
Thanks, I will give it a try. I can close the issue if it's ok for you.

**Comment by nichmorgan** [comment]
As another document said, changing the environment should work, but it doesn't. 
I found the password when looking for the generated image configuration. The problem is that this password differs from the old Raspberry Pi user password because has a typo missing the 'e' letter.

So the password is `raspbrry`.

![image](https://github.com/user-attachments/assets/5e4906e7-0350-472c-881e-f925ba0575ed)
