### ISSUE TITLE
callback pin/channel compatibility

### ISSUE THREAD

**Issue by ArtArt0** [nosix/raspberry-gpio-emulator#4]
Hi!

I am using the GPIO.add_event_detect with GPIO.BOARD setting.

The emulator in the callback gives the channel number instead of the pin number.

The documentation sais it is OK, but on the hardware the default GPIO library gives the pin number in this case!

The old code:
GPIO.add_event_detect(PINS.BUTTON, GPIO.BOTH, callback=waitOnEvent)
which gives the parameter like channel.

I use the folowing workaround:
GPIO.add_event_detect(PINS.BUTTON, GPIO.BOTH, callback=lambda x: waitOnEvent(PINS.BUTTON))
which gives the parameter like pin (PINS.BUTTON)

I dont know it is a problem or not, but definitely a compatible issue...

Regards, Art

**Comment by nosix** [comment]
Thank you for the report.

I have checked the following documents:
https://sourceforge.net/p/raspberry-gpio-python/wiki/Inputs/

No clear description was found. However, it is guessed that the pin number is correct. Therefore, I think that correction is necessary.
