### ISSUE TITLE
Stop emulator from application

### ISSUE THREAD

**Issue by karlTGA** [nosix/raspberry-gpio-emulator#5]
Many thanks for the development of the project. It helps a lot if you don't have to work on the Pi all the time.

But is there a clean way, to stop the emulator and close the gui from the application and not per clicking the gui?
At this moment I have to interrupt the emulator per SIGINT or Keyboard Interrupt what leads to an error message.

**Comment by nosix** [comment]
Thank you for your message.

I'm not good at English, so I use a translation tool to translate and read this. Therefore, I apologize if there is a misunderstanding.

Is it correct in the following?
- You want to stop the emulator and close the GUI.
- You don't want to click on the GUI to stop it.
- So, you interrupt the emulator per SIGINT or Keyboard Interrupt.
- But, you don't want an error message.
- You want to stop from the console without any error messages.

**Comment by karlTGA** [comment]
Thank you for the quick response. And no problem, that you use a translating tool. My English is not the best either and I use translating tools often. 

I think you understand me mostly right, but I don't want to stop the emulator from the console. My Application, that starts the emulator with `import RPi.GPIO as GPIO` should stop the emulator and close the gui, when it ends.

**Comment by nosix** [comment]
I think this can be accomplished by making the following changes.

- Change 

https://github.com/nosix/raspberry-gpio-emulator/blob/f534e90f8c47a7fce3d7367e4aa72c68e9fa75dd/RPi/ui_server.py#L31

to 

```
        if cmd == Pipe.CMD_EXIT:
            self.close()
        elif cmd == Pipe.CMD_CLEANUP:
```

- And add the following code to class UI in ui_client.py

```
    def close(self):
        self.interrupt_main_to_close = False
        self.__pipe.write_bytes([Pipe.CMD_EXIT])
```
- And add the following code to your application code 

```
GPIO.ui.close()
```

Does this sound like the kind of thing you want to do?

**Comment by karlTGA** [comment]
I implemented your changes local. Works like expected. Thank you. 
Do you have plans to implement it permanently?

**Comment by nosix** [comment]
It was released below:

https://hub.docker.com/layers/nosix/raspberry-gpio-emulator/0.3.0/images/sha256-654facb82cd42ce90df988ec09bc32b0b2390b80095b3df42a9ac1cade4afcf5
