### ISSUE TITLE
Failed to compile on windows10

### ISSUE THREAD

**Issue by MkLHX** [nosix/raspberry-gpio-emulator#7]
Hello, i'ad try to use it on windows 10 pro on docker stack and pip failed to install the numpy package.

I going to test with https://github.com/MomsFriendlyRobotCompany/fake_rpi
 to see if i can manage RPi.GPIO emultion.

**Comment by nosix** [comment]
Please give me some more information on how this project is related.

In my Windows 10 Pro environment, the raspberry-gpio-emulator is installed and working.
In addition, I installed Anaconda on Windows 10 Pro and am able to use raspberry-gpio-emulator and numpy there.

**Comment by teich1se** [comment]
I don't know if I had the same issue, but this is where I am stuck at:

I tried loading it on a Windows 10 running Raspian in Virtual Box and it gave the following error when it started:
creating /usr/local/lib/python2.7/dist-packages/RPi

error: could not creat '/usr/local/lib/python2.7/dist-packages/RPi': Permission denied

I just used the permission command:

sudo chown -R $user /usr/local/lib/python2.7 

This worked

**Comment by nosix** [comment]
I think this is not a library issue but an installed environment issue, so I will close this issue.

If you can show me that it's a library issue, I might get started.

**Comment by nosix** [comment]
In addition, since Dockerfile is only considered for execution on macOS, please handle it yourself when using it on Windows.
